CREATE SCHEMA IF NOT EXISTS `user`;
USE `user`;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (

    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL DEFAULT '',
    group_id BIGINT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT NOW(),
    create_by BIGINT NOT NULL DEFAULT 0,
    update_time DATETIME NOT NULL DEFAULT NOW(),
    update_by BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY(id)
);